CREATE DATABASE IF NOT EXISTS correos;
USE correos;

CREATE TABLE IF NOT EXISTS usuarios
(
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(50),
	dni VARCHAR(50),
	edad INTEGER DEFAULT 18,
	correo VARCHAR (100),
	id_subscripcion INT
);

CREATE TABLE IF NOT EXISTS subscripcion
(
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR (100)
);

